In [3]:
import numpy as np

In [4]:
# 1a)
one_dim=np.array([1,2,3,4,5,6,7,8,9,10])
one_dim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# 1b)
two_dim=np.random.rand(3,4)
two_dim

array([[0.15234189, 0.91009687, 0.07609387, 0.74107403],
       [0.61340752, 0.56229882, 0.87718103, 0.02652939],
       [0.96057097, 0.84475718, 0.5560976 , 0.54290274]])

In [6]:
# 1c)
three_dim=np.zeros((2,3,4))
three_dim

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
# 2a)
a=np.array([2,4,6,3])
b=np.array([1,5,2,7])

add=a+b
add

array([ 3,  9,  8, 10])

In [8]:
sub=a-b
sub

array([ 1, -1,  4, -4])

In [9]:
mult=a*b
mult

array([ 2, 20, 12, 21])

In [10]:
div=a/b
div

array([2.        , 0.8       , 3.        , 0.42857143])

In [11]:
# 2b)
mean=np.mean(a)
mean

3.75

In [12]:
median=np.median(b)
median

3.5

In [13]:
stddev=np.std(a)
stddev

1.479019945774904

In [15]:
# 2c)
a

array([2, 4, 6, 3])

In [20]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape((3,4))
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
# 3a
arr=np.array([[1,2,3,4,5],[2,4,1,6,7]])
arr

array([[1, 2, 3, 4, 5],
       [2, 4, 1, 6, 7]])

In [23]:
row=arr[0]
row

array([1, 2, 3, 4, 5])

In [26]:
column=arr[:,4]
column

array([5, 7])

In [28]:
# 3b)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
reverse=np.flip(a)
reverse

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [31]:
arr

array([[1, 2, 3, 4, 5],
       [2, 4, 1, 6, 7]])

In [32]:
condition=arr[arr>3]
condition

array([4, 5, 4, 6, 7])

In [33]:
# 4
scalar=20
new_arr=arr+scalar
new_arr

array([[21, 22, 23, 24, 25],
       [22, 24, 21, 26, 27]])

In [38]:
# 4b)
a=np.array([2,4,6,8])
b=np.array([[2,5,1,4],[1,2,3,4]])
mult=b*a
mult

array([[ 4, 20,  6, 32],
       [ 2,  8, 18, 32]])

In [39]:
# 5a)
a=np.array([2,3,1,5])
b=np.array([1,5,4,8])
c=np.dot(a,b)
c

61

In [41]:
# 5b)
a=np.array([[1,3],[4,1]])
b=np.array([[8,1],[2,9]])
c=np.matmul(a,b)
c

array([[14, 28],
       [34, 13]])

In [42]:
# 5c)
a

array([[1, 3],
       [4, 1]])

In [43]:
inverse=np.linalg.inv(a)
inverse

array([[-0.09090909,  0.27272727],
       [ 0.36363636, -0.09090909]])

In [44]:
det_a=np.linalg.det(a)
det_a

-11.000000000000002